### ISSUE TITLE
Nano-ReactNative brings its own version of ReactNative (yarn)

### ISSUE THREAD

**Issue by ca057** [ClickSimply/Nano-ReactNative#1]
Hello,

when installing the library with `yarn add nano-react-native`, I get an error when running the bundler as I have two versions of ReactNative installed (one via the actual project itself).

Shouldn't `react-native` be listed as `peerDependency` instead as a real `dependency`?

Best! Christian

**Comment by ClickSimply** [comment]
Hey thanks for the heads up and the pull request, marking this resolved.
